CREATE TABLE IF NOT EXISTS request (
	id INTEGER PRIMARY KEY,
	content TEXT NOT NULL,
	uuid TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS response (
	id INTEGER PRIMARY KEY,
	content TEXT NOT NULL,
	request_id INTEGER NOT NULL,
	FOREIGN KEY(request_id) REFERENCES request(id) ON DELETE CASCADE
)