CREATE TABLE IF NOT EXISTS request (
	id INTEGER PRIMARY KEY,
	content TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))
);
CREATE TABLE IF NOT EXISTS response (
	id INTEGER PRIMARY KEY,
	content TEXT NOT NULL,
	request_id INTEGER NOT NULL,
	created_at TEXT NOT NULL DEFAULT(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')),
	FOREIGN KEY(request_id) REFERENCES request(id) ON DELETE CASCADE
)